// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC03J37EBhJOejLrMV6DPYCsUaHUkL6qFo',
    appId: '1:929607489635:android:2247d3fde03685f0140056',
    messagingSenderId: '929607489635',
    projectId: 'medicare-348a1',
    storageBucket: 'medicare-348a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKEyJWUNljfw5eBAO35QImv8-8bTVjWJ4',
    appId: '1:929607489635:ios:bb68e9c5389ca7de140056',
    messagingSenderId: '929607489635',
    projectId: 'medicare-348a1',
    storageBucket: 'medicare-348a1.firebasestorage.app',
    iosBundleId: 'com.example.medicare',
  );
}
